services:
  isaac_sim:
    image: nvcr.io/nvidia/isaac-sim:4.5.0
    container_name: isaac-sim
    entrypoint: bash
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SDL_VIDEODRIVER=x11
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./isaac_ws:/root/isaac_ws
      - ./bashrc_isaac:/root/.bashrc
    network_mode: host
    stdin_open: true
    tty: true

  ros2_humble:
    image: osrf/ros:humble-desktop-full-jammy
    container_name: ros2_humble
    volumes:
      - ./humble_ws:/root/humble_ws
      - ./bashrc_ros2:/root/.bashrc
    network_mode: host
    stdin_open: true
    tty: true

  ros1_bridge:
    image: osrf/ros:foxy-ros1-bridge
    container_name: ros1_bridge
    volumes:
      - ./ros1_bridge:/root/ros1_bridge
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_IP=127.0.0.1

