services:
  isaac_sim:
    build: ./isaac_ws
    container_name: isaac-sim
    runtime: nvidia
    working_dir: /root
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SDL_VIDEODRIVER=x11
      - ACCEPT_EULA=Y
      - PRIVACY_CONSENT=Y
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./isaac_ws:/root/isaac_ws
    network_mode: host
    stdin_open: true
    tty: true